name: 🌐 Nuova normalizzazione titolo
description: Proponi una coppia MAL → AnimeSaturn da aggiungere alla funzione normalizeTitleForSearch
title: "[NORMALIZZA]: "
labels: ["richiesta", "normalizzazione"]

body:
  - type: markdown
    attributes:
      value: |
        Compila i campi sottostanti seguendo l’esempio:
        | Campo | Esempio |
        |-------|---------|
        | MAL English name | Slam Dunk: National Domination! Sakuragi Hanamichi |
        | AnimeSaturn name | Slam Dunk: Zenkoku Seiha Da! Sakuragi Hanamichi |

  - type: input
    id: mal_name
    attributes:
      label: MAL English name
      placeholder: Slam Dunk National Domination! Sakuragi Hanamichi
    validations:
      required: true

  - type: input
    id: as_name
    attributes:
      label: AnimeSaturn name
      placeholder: Slam Dunk Zenkoku Seiha Da! Sakuragi Hanamichi
    validations:
      required: true

  - type: checkboxes
    id: conferme
    attributes:
      label: Conferme
      options:
        - label: Ho controllato che la coppia non sia già presente nel file
          required: true
