name: Crea PR da Issue di normalizzazione

on:
  issues:
    types: [opened, edited]

jobs:
  generate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Aggiungi label normalizzazione se manca
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: normalizzazione

      - name: Debug issue body
        run: |
          echo "${{ github.event.issue.body }}"

      - id: parse
        run: |
          MAL_NAME=$(echo "${{ github.event.issue.body }}" | awk '/^### MAL English name/{getline; print $0}' | xargs)
          AS_NAME=$(echo "${{ github.event.issue.body }}" | awk '/^### AnimeSaturn name/{getline; print $0}' | xargs)
          echo "mal_name=$MAL_NAME" >> $GITHUB_OUTPUT
          echo "as_name=$AS_NAME" >> $GITHUB_OUTPUT
          echo "Parsed MAL name: '$MAL_NAME'"
          echo "Parsed AS name: '$AS_NAME'"

      - name: Aggiungi riga di normalizzazione
        run: |
          python3 -c '
          import re

          mal_name = "${{ steps.parse.outputs.mal_name }}"
          as_name = "${{ steps.parse.outputs.as_name }}"

          with open("src/providers/animesaturn-provider.ts", "r", encoding="utf-8") as f:
              content = f.read()

          pattern = r"(.*?)(// Qui puoi aggiungere altre normalizzazioni custom)"
          replacement = r"\1    \"" + mal_name + "\": \"" + as_name + "\",\n    \2"

          new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

          with open("src/providers/animesaturn-provider.ts", "w", encoding="utf-8") as f:
              f.write(new_content)

          print(f"Added normalization: \"{mal_name}\": \"{as_name}\"")
          '

      - name: Crea PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat(normalize): add \"${{ steps.parse.outputs.mal_name }}\""
          branch: "normalizza-${{ github.event.issue.number }}"
          title: "Normalizzazione: ${{ steps.parse.outputs.mal_name }}"
          body: |
            ## 🔗 Nuova normalizzazione

            | Campo | Valore |
            |-------|--------|
            | **MAL English name** | ${{ steps.parse.outputs.mal_name }} |
            | **AnimeSaturn name** | ${{ steps.parse.outputs.as_name }} |

            ### Checklist
            - [ ] Compilazione corretta secondo Issue
            - [ ] I test esistenti passano
            - [ ] Non rompe altre normalizzazioni

            _Questa PR è stata generata automaticamente dalla Issue #${{ github.event.issue.number }}._ 
