name: Crea PR da Issue di normalizzazione

on:
  issues:
    types: [opened]

jobs:
  generate-pr:
    if: contains(github.event.issue.labels.*.name, 'normalizza')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Estrai i dati dal corpo dell'Issue Form
      - id: parse
        run: |
          MAL_NAME=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=\*\*MAL English name\*\*\s*\|\s*)(.+)')
          AS_NAME=$(echo "${{ github.event.issue.body }}"  | grep -oP '(?<=\*\*AnimeSaturn name\*\*\s*\|\s*)(.+)')
          echo "mal_name=$MAL_NAME" >> $GITHUB_OUTPUT
          echo "as_name=$AS_NAME"   >> $GITHUB_OUTPUT

      # 2. Applica la patch al file TypeScript
      - name: Aggiungi riga di normalizzazione
        run: |
          FILE="src/providers/animesaturn-provider.ts"
          MAL_ESCAPED=$(printf "%s" "${{ steps.parse.outputs.mal_name }}" | sed "s/'/\\\'/g")
          AS_ESCAPED=$(printf "%s" "${{ steps.parse.outputs.as_name }}"  | sed "s/'/\\\'/g")

          # inserisce la nuova riga prima del commento desiderato
          awk -v mal="$MAL_ESCAPED" -v as="$AS_ESCAPED" '
            /\/\/ Qui puoi aggiungere altre normalizzazioni custom/ && !done {
              print "'"'"'"'"'"'" mal "'"'"'"'"'"'": "'"'"'"'"'"'" as "'"'"'"'"'"'","
              done=1
            }
            { print }
          ' "$FILE" > tmp && mv tmp "$FILE"

      # 3. Crea la Pull Request
      - name: Crea PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat(normalize): add \"${{ steps.parse.outputs.mal_name }}\""
          branch: "normalizza-${{ github.event.issue.number }}"
          title: "Normalizzazione: ${{ steps.parse.outputs.mal_name }}"
          body: |
            | Campo | Valore |
            |-------|--------|
            | **MAL English name** | ${{ steps.parse.outputs.mal_name }} |
            | **AnimeSaturn name** | ${{ steps.parse.outputs.as_name }} |

            Closes #${{ github.event.issue.number }}
